"""spine — the ten tables a governed turn writes

Revision 0001, the V2 rebuild's first and only migration so far: users,
conversations, messages, tasks, task_status_events, plans, llm_calls,
tool_calls, approvals, audit_events (ARCHITECTURE_V2 §2's db/ layer).

Autogenerated from `sunil.db.models` against the pinned
`pgvector/pgvector:0.8.6-pg17` image and applied there — not hand-written, so
the migration and the models cannot disagree. Portable by construction (ADR-001):
`JSON().with_variant(JSONB, "postgresql")`, no native ENUMs (CHECK constraints
instead), no server-side defaults.

Revision ID: 0001
Revises: 
Create Date: 2026-09-11 08:11:37.594530+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('tool', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('args_hash', sa.String(length=64), nullable=False),
    sa.Column('params_redacted', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('continuation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('decided_at', sa.String(length=40), nullable=True),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('decision_reason', sa.String(length=1000), nullable=True),
    sa.Column('consumed_at', sa.String(length=40), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'refused', 'expired', 'consumed')", name='ck_approvals_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_conversation_id'), 'approvals', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_approvals_request_id'), 'approvals', ['request_id'], unique=False)
    op.create_index('ix_approvals_status_expires', 'approvals', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_approvals_task_id'), 'approvals', ['task_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("stage IN ('request_received', 'context_loaded', 'memory_retrieved', 'model_selected', 'llm_io', 'plan_created', 'agent_started', 'tool_requested', 'permission_decision', 'tool_result', 'agent_result', 'final_response')", name='ck_audit_events_stage'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'seq', name='uq_audit_events_request_seq')
    )
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('channel_label', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("channel IN ('web', 'service')", name='ck_conversations_channel'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('validated_plan_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('tool', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('adapter_kind', sa.String(length=20), nullable=True),
    sa.Column('server_id', sa.String(length=100), nullable=True),
    sa.Column('args_hash', sa.String(length=64), nullable=True),
    sa.Column('params_redacted', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('permission_decision', sa.String(length=20), nullable=True),
    sa.Column('permission_reason', sa.Text(), nullable=True),
    sa.Column('approval_id', sa.String(length=36), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('error_kind', sa.String(length=50), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalised_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("outcome IN ('ok', 'error', 'not_executed')", name='ck_tool_calls_outcome'),
    sa.CheckConstraint("permission_decision IN ('allow', 'deny', 'ask_user')", name='ck_tool_calls_permission_decision'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_approval_id'), 'tool_calls', ['approval_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_request_id'), 'tool_calls', ['request_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_task_id'), 'tool_calls', ['task_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_validated_plan_id'), 'tool_calls', ['validated_plan_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('resumed_from_approval_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_conversation_seq', 'messages', ['conversation_id', 'seq'], unique=False)
    op.create_index(op.f('ix_messages_request_id'), 'messages', ['request_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_agent', sa.String(length=100), nullable=False),
    sa.Column('privacy_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_kind', sa.String(length=50), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'failed', 'parked')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_conversation_id'), 'tasks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tasks_request_id'), 'tasks', ['request_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('privacy_class', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_model', sa.String(length=100), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('request_messages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('request_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('finish_reason', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_micro_usd', sa.BigInteger(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_kind', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("purpose IN ('plan', 'analysis', 'final_response')", name='ck_llm_calls_purpose'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_request_id'), 'llm_calls', ['request_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_task_id'), 'llm_calls', ['task_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('raw_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_request_id'), 'plans', ['request_id'], unique=False)
    op.create_index(op.f('ix_plans_task_id'), 'plans', ['task_id'], unique=False)
    op.create_table('task_status_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_events_task_id'), 'task_status_events', ['task_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_task_status_events_task_id'), table_name='task_status_events')
    op.drop_table('task_status_events')
    op.drop_index(op.f('ix_plans_task_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_request_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_llm_calls_task_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_request_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_tasks_request_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_conversation_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_messages_request_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_seq', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_index(op.f('ix_tool_calls_validated_plan_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_task_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_request_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_approval_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_approvals_task_id'), table_name='approvals')
    op.drop_index('ix_approvals_status_expires', table_name='approvals')
    op.drop_index(op.f('ix_approvals_request_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_conversation_id'), table_name='approvals')
    op.drop_table('approvals')
