"""task_status_events.id — UUID string to a database-assigned monotonic integer

C6's ``TaskDetail`` promises ``status_events`` "Ascending ``at`` (a timeline);
ties keep write order", and `api/routes/tasks.py` implements that promise as
``ORDER BY at ASC, id ASC``. Its own comment reasons from "a table whose id is a
monotonic integer" — which was true of Stream D's read model
(`ops_read_model.py`: ``Column("id", Integer, primary_key=True,
autoincrement=True)``) and false of the schema production runs, where
`db/models.py` declared ``String(36)`` filled with ``uuid4``. A UUID sorts by
nothing, so the tie in "ties keep write order" was broken arbitrarily; because
the C6 suite seeds the read model's own metadata, no test could see it
(integration-w1 §5.2).

**Why the integer wins rather than the UUID.** Nothing demands a UUID here:
``task_status_events.id`` carries no foreign key, and C6 does not put it on the
wire at all (``TaskStatusEvent.required`` is ``[from_status, to_status, at]``,
`C6-ops-reads-openapi.yaml`). The only job the column has is the one the
contract sentence gives it, and a monotonic integer is the only one of the two
candidates that can do it. The alternative reading — keep the UUID and drop the
tiebreak — would leave equal-``at`` events in whatever order the planner
returned, i.e. would delete a contract promise rather than implement it.

**Rows.** The column is rebuilt, not converted: the old values are UUIDs, so
there is no order in them to preserve and no cast that would invent one. On a
populated table Postgres assigns the identity values in scan order; the rows
keep every column that carries meaning (``task_id``, ``from_status``,
``to_status``, ``at``) and gain an ordering key they did not have. On the
deployments this actually reaches — fresh ones, since ``upgrade head`` was
impossible until the revision before this one — the table is empty.

Postgres-shaped DDL (``ADD COLUMN … GENERATED BY DEFAULT AS IDENTITY``, then the
primary key). SQLite cannot add a primary key in place; it does not need to,
because on SQLite the schema is built with ``create_all`` from `db/models.py`,
which declares the same ``INTEGER PRIMARY KEY``.

Revision ID: 0004
Revises: d4approvals0001
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "d4approvals0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE = "task_status_events"
#: Postgres' own name for the constraint `0001` created as
#: `sa.PrimaryKeyConstraint("id")` — reused so the rebuilt key is not a rename.
PK = "task_status_events_pkey"


def upgrade() -> None:
    # Dropping the column drops the primary key that was on it.
    op.drop_column(TABLE, "id")
    op.add_column(
        TABLE,
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
    )
    op.create_primary_key(PK, TABLE, ["id"])


def downgrade() -> None:
    """Back to a string id — with the integer preserved INSIDE the value.

    The original UUIDs are gone and minting fresh ones would state, in the
    column a reader trusts as an identity, something no row ever had. `tse-<n>`
    is derived from the id this revision assigned, so a downgraded row's id says
    where it came from and still sorts with its siblings.
    """
    op.drop_constraint(PK, TABLE, type_="primary")
    op.add_column(TABLE, sa.Column("legacy_id", sa.String(length=36), nullable=True))
    # Literal SQL, no interpolation of anything but this module's own constants.
    op.execute("UPDATE task_status_events SET legacy_id = 'tse-' || id")
    op.drop_column(TABLE, "id")
    op.alter_column(TABLE, "legacy_id", new_column_name="id", nullable=False)
    op.create_primary_key(PK, TABLE, ["id"])
