"""C4 approvals table (Stream D).

Revision ID: d4approvals0001
Revises: 0003
Create Date: 2026-09-11

Coordination note — LINEARISED at integration-w1 (2026-09-12)
------------------------------------------------------------
This revision shipped as a **branch root** (``down_revision = None`` + the
``approvals`` branch label) because Stream D and the spine lane built in
parallel worktrees and the spine's initial revision id did not exist here yet.
It does now, so the graph is linearised, exactly as the note below predicted
("set ``down_revision = <spine initial revision>`` here and delete
``branch_labels``"). Two heads meant ``alembic upgrade head`` was ambiguous and
a fresh deployment could not migrate at all.

**Parent = ``0003``, the spine's head, not ``0001``.** Nothing in this DDL
depends on ``0002`` (``tasks.project_key``) or ``0003`` (``tasks.priority``) —
the table still has no foreign keys into the spine's schema, and C4's
``task_id``/``conversation_id``/``request_id`` remain contract strings
(``core/approvals/table.py``). ``0001`` would therefore satisfy the dependency.
It is the head that is chosen anyway, because attaching to anything earlier
recreates on the next migration exactly the condition being fixed here: a second
head. A linear history has one answer to "what does ``head`` mean", and the cost
of the stricter parent is an ordering constraint nobody needs rather than an
ambiguity every deployment hits.

The other half of the fix is in ``0001``: its autogenerated ``approvals`` table
— the duplicate its own note warned against ("what must NOT happen is a second
revision also creating an ``approvals`` table") — was removed, so this file is
again the only schema for C4's table. See ``0001``'s amendment note for why an
applied revision was edited rather than superseded.

Two schema decisions are contract requirements, not preferences, and a reviewer
should check them here specifically:

1. ``status`` has **no server default** (C4 §1, OpenAPI ``ApprovalStatus``;
   central-memory lesson 2026-08-17). A creation path that omits the status must
   fail loudly instead of minting a row that reads as decided. The CHECK
   constraint bounds the column to C4's five values.
2. ``continuation`` is ``NOT NULL`` on this row, which is what makes C4 §1's
   restart-safety rule ("the park INSERT commits in the same transaction as the
   persisted continuation state") true by construction: one INSERT, one row.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "d4approvals0001"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=64), primary_key=True),
        # No server_default — C4 §1. See the module docstring.
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("agent_id", sa.String(length=128), nullable=False),
        sa.Column("tool", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=128), nullable=False),
        sa.Column("args_hash", sa.String(length=128), nullable=False),
        sa.Column("params_redacted", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("continuation", sa.JSON(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=128), nullable=True),
        sa.Column("decision_reason", sa.String(length=1000), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'refused', 'expired', 'consumed')",
            name="ck_approvals_status",
        ),
    )
    # The sweeper's two guards (C4 §1).
    op.create_index(
        "ix_approvals_status_expires_at", "approvals", ["status", "expires_at"]
    )
    op.create_index(
        "ix_approvals_status_decided_at", "approvals", ["status", "decided_at"]
    )
    # C4 §6.5's page order, so the keyset cursor is an index scan.
    op.create_index("ix_approvals_created_at_id", "approvals", ["created_at", "id"])
    op.create_index("ix_approvals_task_id", "approvals", ["task_id"])


def downgrade() -> None:
    op.drop_index("ix_approvals_task_id", table_name="approvals")
    op.drop_index("ix_approvals_created_at_id", table_name="approvals")
    op.drop_index("ix_approvals_status_decided_at", table_name="approvals")
    op.drop_index("ix_approvals_status_expires_at", table_name="approvals")
    op.drop_table("approvals")
