"""initial — the twelve M1 tables (ARCHITECTURE_V1.md §7.3).

users, conversations, messages, workflows, tasks, task_status_events,
plans, tool_calls, approvals, memories, llm_calls, audit_events.

Started as an `--autogenerate` draft, then hand-reviewed (ADR-002: drafts
are never committed as-is) — table/column shapes match `sunil.db.models`
exactly; drop order in `downgrade()` was verified to respect every foreign
key (children before parents) rather than assumed.

Revision ID: 0001
Revises:
Create Date: 2026-08-14
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("stage IN ('message_received', 'context_loaded', 'memory_retrieved', 'model_selected', 'llm_io', 'plan_created', 'agent_started', 'tool_requested', 'permission_decision', 'tool_result', 'agent_result', 'final_response')", name='ck_audit_events_stage'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'seq', name='uq_audit_events_request_seq')
    )
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('security_settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('active_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_request_id', sa.String(length=36), nullable=False),
    sa.Column('source_task_id', sa.String(length=36), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_policy', sa.String(length=20), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('retention_class', sa.String(length=20), nullable=False),
    sa.Column('training_eligible', sa.Boolean(), nullable=False),
    sa.CheckConstraint("capture_policy IN ('none', 'metadata_only', 'redacted_full', 'full_local_only')", name='ck_memories_capture_policy'),
    sa.CheckConstraint("retention_class IN ('transient', 'standard', 'long', 'permanent')", name='ck_memories_retention_class'),
    sa.CheckConstraint("sensitivity IN ('public', 'internal', 'confidential', 'restricted')", name='ck_memories_sensitivity'),
    sa.CheckConstraint("type IN ('short_term', 'long_term', 'structured', 'knowledge', 'preference')", name='ck_memories_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_source_request_id'), 'memories', ['source_request_id'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('schedule', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'failed')", name='ck_workflows_status'),
    sa.CheckConstraint("trigger IN ('chat_message')", name='ck_workflows_trigger'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_owner_user_id'), 'workflows', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_workflows_request_id'), 'workflows', ['request_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_micro_usd', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_policy', sa.String(length=20), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('retention_class', sa.String(length=20), nullable=False),
    sa.Column('training_eligible', sa.Boolean(), nullable=False),
    sa.CheckConstraint("capture_policy IN ('none', 'metadata_only', 'redacted_full', 'full_local_only')", name='ck_messages_capture_policy'),
    sa.CheckConstraint("retention_class IN ('transient', 'standard', 'long', 'permanent')", name='ck_messages_retention_class'),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='ck_messages_role'),
    sa.CheckConstraint("sensitivity IN ('public', 'internal', 'confidential', 'restricted')", name='ck_messages_sensitivity'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_conversation_seq', 'messages', ['conversation_id', 'seq'], unique=False)
    op.create_index(op.f('ix_messages_request_id'), 'messages', ['request_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('parent_task_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_agent', sa.String(length=100), nullable=False),
    sa.Column('privacy_level', sa.String(length=20), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_kind', sa.String(length=50), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'failed')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_conversation_id'), 'tasks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tasks_request_id'), 'tasks', ['request_id'], unique=False)
    op.create_index(op.f('ix_tasks_workflow_id'), 'tasks', ['workflow_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('capability', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('request_system', sa.Text(), nullable=True),
    sa.Column('request_messages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('request_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('stop_reason', sa.String(length=50), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_micro_usd', sa.BigInteger(), nullable=False),
    sa.Column('pricing_version', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_kind', sa.String(length=50), nullable=True),
    sa.Column('provider_request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_policy', sa.String(length=20), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('retention_class', sa.String(length=20), nullable=False),
    sa.Column('training_eligible', sa.Boolean(), nullable=False),
    sa.CheckConstraint("capture_policy IN ('none', 'metadata_only', 'redacted_full', 'full_local_only')", name='ck_llm_calls_capture_policy'),
    sa.CheckConstraint("purpose IN ('plan', 'analysis', 'final_response')", name='ck_llm_calls_purpose'),
    sa.CheckConstraint("retention_class IN ('transient', 'standard', 'long', 'permanent')", name='ck_llm_calls_retention_class'),
    sa.CheckConstraint("sensitivity IN ('public', 'internal', 'confidential', 'restricted')", name='ck_llm_calls_sensitivity'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_request_id'), 'llm_calls', ['request_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_task_id'), 'llm_calls', ['task_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('raw_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_policy', sa.String(length=20), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('retention_class', sa.String(length=20), nullable=False),
    sa.Column('training_eligible', sa.Boolean(), nullable=False),
    sa.CheckConstraint("capture_policy IN ('none', 'metadata_only', 'redacted_full', 'full_local_only')", name='ck_plans_capture_policy'),
    sa.CheckConstraint("retention_class IN ('transient', 'standard', 'long', 'permanent')", name='ck_plans_retention_class'),
    sa.CheckConstraint("sensitivity IN ('public', 'internal', 'confidential', 'restricted')", name='ck_plans_sensitivity'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_request_id'), 'plans', ['request_id'], unique=False)
    op.create_index(op.f('ix_plans_task_id'), 'plans', ['task_id'], unique=False)
    op.create_table('task_status_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_status_events_task_id'), 'task_status_events', ['task_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('validated_plan_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('tool', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('permission_decision', sa.String(length=20), nullable=False),
    sa.Column('permission_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_kind', sa.String(length=50), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capture_policy', sa.String(length=20), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=False),
    sa.Column('retention_class', sa.String(length=20), nullable=False),
    sa.Column('training_eligible', sa.Boolean(), nullable=False),
    sa.CheckConstraint("capture_policy IN ('none', 'metadata_only', 'redacted_full', 'full_local_only')", name='ck_tool_calls_capture_policy'),
    sa.CheckConstraint("permission_decision IN ('allow', 'deny', 'ask_user')", name='ck_tool_calls_permission_decision'),
    sa.CheckConstraint("retention_class IN ('transient', 'standard', 'long', 'permanent')", name='ck_tool_calls_retention_class'),
    sa.CheckConstraint("sensitivity IN ('public', 'internal', 'confidential', 'restricted')", name='ck_tool_calls_sensitivity'),
    sa.CheckConstraint("status IN ('ok', 'error', 'not_executed')", name='ck_tool_calls_status'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['validated_plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_request_id'), 'tool_calls', ['request_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_task_id'), 'tool_calls', ['task_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_validated_plan_id'), 'tool_calls', ['validated_plan_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('tool_call_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_decision', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_approvals_status'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_request_id'), 'approvals', ['request_id'], unique=False)
    op.create_index(op.f('ix_approvals_task_id'), 'approvals', ['task_id'], unique=False)
    op.create_index(op.f('ix_approvals_tool_call_id'), 'approvals', ['tool_call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_tool_call_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_task_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_request_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_tool_calls_validated_plan_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_task_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_request_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_task_status_events_task_id'), table_name='task_status_events')
    op.drop_table('task_status_events')
    op.drop_index(op.f('ix_plans_task_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_request_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_llm_calls_task_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_request_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_tasks_workflow_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_request_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_conversation_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_messages_request_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_seq', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_workflows_request_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_owner_user_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_source_request_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
